project:
  type: website

website:
  title: "Devin Simmons"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - text: "Assignments"
        menu: 
          - href: assign01.qmd
            text: "Assignment 1"
          - href: assign02.qmd
            text: "Assignment 2"
      - href: coverletter.pdf
        text: "Resume"
      
format:
  html:
    theme: xxx
    css: styles.css
    toc: true

editor: visual